title = "Bearking's Stronghold"
logo = "img/ok.png"
copyright = "th3_5had0w, CC-BY-SA"

[author]
name = "th3_5had0w"
image = "img/ok.png"
headline = "will hac for food"
bio = "hecku"
links = [
  { github = "https://github.com/th3-5had0w" },
]
